import "./globals.css";
import { Inter } from "next/font/google";
import Header from "../lib/header";
import Footer from "../lib/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            {/* <body className={inter.className + " bg-gray-200"}>{children}</body> */}
            <body className="bg-gray-200 flex flex-col h-screen">
                <Header loggedIn={false} />
                <main
                    className={
                        inter.className + "h-full overflow-y-hidden mb-auto"
                    }
                >
                    {/* className="flex flex-col max-w-screen-lg justify-center items-center w-full h-full mx-auto" */}
                    {children}
                </main>
                <Footer />
            </body>
        </html>
    );
}
