// import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
    return <>{children};</>;
    // < lang="en">
    //     <body className={inter.className + " bg-gray-200"}>{children}</body>
    // </>
}
